require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FamiliaController do

  # This should return the minimal set of attributes required to create a valid
  # Familium. As you add validations to Familium, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all familia as @familia" do
      familium = Familium.create! valid_attributes
      get :index
      assigns(:familia).should eq([familium])
    end
  end

  describe "GET show" do
    it "assigns the requested familium as @familium" do
      familium = Familium.create! valid_attributes
      get :show, :id => familium.id
      assigns(:familium).should eq(familium)
    end
  end

  describe "GET new" do
    it "assigns a new familium as @familium" do
      get :new
      assigns(:familium).should be_a_new(Familium)
    end
  end

  describe "GET edit" do
    it "assigns the requested familium as @familium" do
      familium = Familium.create! valid_attributes
      get :edit, :id => familium.id
      assigns(:familium).should eq(familium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Familium" do
        expect {
          post :create, :familium => valid_attributes
        }.to change(Familium, :count).by(1)
      end

      it "assigns a newly created familium as @familium" do
        post :create, :familium => valid_attributes
        assigns(:familium).should be_a(Familium)
        assigns(:familium).should be_persisted
      end

      it "redirects to the created familium" do
        post :create, :familium => valid_attributes
        response.should redirect_to(Familium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved familium as @familium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Familium.any_instance.stub(:save).and_return(false)
        post :create, :familium => {}
        assigns(:familium).should be_a_new(Familium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Familium.any_instance.stub(:save).and_return(false)
        post :create, :familium => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested familium" do
        familium = Familium.create! valid_attributes
        # Assuming there are no other familia in the database, this
        # specifies that the Familium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Familium.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => familium.id, :familium => {'these' => 'params'}
      end

      it "assigns the requested familium as @familium" do
        familium = Familium.create! valid_attributes
        put :update, :id => familium.id, :familium => valid_attributes
        assigns(:familium).should eq(familium)
      end

      it "redirects to the familium" do
        familium = Familium.create! valid_attributes
        put :update, :id => familium.id, :familium => valid_attributes
        response.should redirect_to(familium)
      end
    end

    describe "with invalid params" do
      it "assigns the familium as @familium" do
        familium = Familium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Familium.any_instance.stub(:save).and_return(false)
        put :update, :id => familium.id, :familium => {}
        assigns(:familium).should eq(familium)
      end

      it "re-renders the 'edit' template" do
        familium = Familium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Familium.any_instance.stub(:save).and_return(false)
        put :update, :id => familium.id, :familium => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested familium" do
      familium = Familium.create! valid_attributes
      expect {
        delete :destroy, :id => familium.id
      }.to change(Familium, :count).by(-1)
    end

    it "redirects to the familia list" do
      familium = Familium.create! valid_attributes
      delete :destroy, :id => familium.id
      response.should redirect_to(familia_url)
    end
  end

end
